<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiscordScraper.Core\DiscordScraper.Core.csproj" />
    <ProjectReference Include="..\DiscordScraper.Discord\DiscordScraper.Discord.csproj" />
    <ProjectReference Include="..\DiscordScraper.Storage\DiscordScraper.Storage.csproj" />
  </ItemGroup>

</Project>
