<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.MongoDb" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="MassTransit.TestFramework" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Pgvector" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Testcontainers" />
    <PackageReference Include="Testcontainers.MongoDb" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.RabbitMq" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
    <Using Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DiscordScraper.Contracts\DiscordScraper.Contracts.csproj" />
    <ProjectReference Include="..\..\src\DiscordScraper.Core\DiscordScraper.Core.csproj" />
    <ProjectReference Include="..\..\src\DiscordScraper.Discord\DiscordScraper.Discord.csproj" />
    <ProjectReference Include="..\..\src\DiscordScraper.Enrichment\DiscordScraper.Enrichment.csproj" />
    <ProjectReference Include="..\..\src\DiscordScraper.Read\DiscordScraper.Read.csproj" />
    <ProjectReference Include="..\..\src\DiscordScraper.Rendering\DiscordScraper.Rendering.csproj" />
    <ProjectReference Include="..\..\src\DiscordScraper.Write\DiscordScraper.Write.csproj" />
    <ProjectReference Include="..\DiscordScraper.TestSupport\DiscordScraper.TestSupport.csproj" />
  </ItemGroup>

</Project>
