<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiscordScraper.Ingestion\DiscordScraper.Ingestion.csproj" />
    <ProjectReference Include="..\DiscordScraper.ServiceDefaults\DiscordScraper.ServiceDefaults.csproj" />
    <ProjectReference Include="..\DiscordScraper.Storage\DiscordScraper.Storage.csproj" />
  </ItemGroup>

</Project>
