// <auto-generated />
using System;
using DiscordScraper.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace DiscordScraper.Storage.Migrations
{
    [DbContext(typeof(DiscordScraperDbContext))]
    partial class DiscordScraperDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiscordScraper.Storage.Entities.ChannelCurrentView", b =>
                {
                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.ToTable((string)null);

                    b.ToView("channels_current", (string)null);
                });

            modelBuilder.Entity("DiscordScraper.Storage.Entities.GuildCurrentView", b =>
                {
                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.ToTable((string)null);

                    b.ToView("guilds_current", (string)null);
                });

            modelBuilder.Entity("DiscordScraper.Storage.Entities.IngestionRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("ItemsProcessed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("items_processed");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Worker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("worker");

                    b.HasKey("Id");

                    b.HasIndex("Worker", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ingestion_runs_worker_started");

                    b.ToTable("ingestion_runs", (string)null);
                });

            modelBuilder.Entity("DiscordScraper.Storage.Entities.MessageEnrichmentEntity", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<string>("EmbeddingModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("embedding_model");

                    b.Property<DateTimeOffset>("EnrichedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enriched_at");

                    b.Property<int>("EnrichmentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("enrichment_version");

                    b.Property<bool>("IsSubstantive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_substantive");

                    b.Property<string>("QdrantPointId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qdrant_point_id");

                    b.PrimitiveCollection<string[]>("TopicTags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("topic_tags")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.HasKey("MessageId");

                    b.HasIndex("EnrichmentVersion")
                        .HasDatabaseName("ix_message_enrichments_version");

                    b.HasIndex("TopicTags")
                        .HasDatabaseName("ix_message_enrichments_topic_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TopicTags"), "gin");

                    b.ToTable("message_enrichments", (string)null);
                });

            modelBuilder.Entity("DiscordScraper.Storage.Entities.MessageEntity", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("author_id");

                    b.Property<bool>("AuthorIsBot")
                        .HasColumnType("boolean")
                        .HasColumnName("author_is_bot");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author_name");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<NpgsqlTsVector>("ContentTsv")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("content_tsv")
                        .HasComputedColumnSql("to_tsvector('english', content)", true);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<bool>("HasAttachments")
                        .HasColumnType("boolean")
                        .HasColumnName("has_attachments");

                    b.Property<long?>("ReplyToId")
                        .HasColumnType("bigint")
                        .HasColumnName("reply_to_id");

                    b.Property<long>("RootChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("root_channel_id");

                    b.Property<long?>("ThreadId")
                        .HasColumnType("bigint")
                        .HasColumnName("thread_id");

                    b.HasKey("MessageId");

                    b.HasIndex("ContentTsv")
                        .HasDatabaseName("ix_messages_content_tsv");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ContentTsv"), "gin");

                    b.HasIndex("ReplyToId")
                        .HasDatabaseName("ix_messages_reply_to_id")
                        .HasFilter("reply_to_id IS NOT NULL");

                    b.HasIndex("ThreadId")
                        .HasDatabaseName("ix_messages_thread_id")
                        .HasFilter("thread_id IS NOT NULL");

                    b.HasIndex("ChannelId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_messages_channel_created");

                    b.HasIndex("GuildId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_messages_guild_created");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("DiscordScraper.Storage.Entities.RawChannelEntity", b =>
                {
                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("ChannelId", "FetchedAt");

                    b.ToTable("raw_channels", (string)null);
                });

            modelBuilder.Entity("DiscordScraper.Storage.Entities.RawGuildEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("GuildId", "FetchedAt");

                    b.ToTable("raw_guilds", (string)null);
                });

            modelBuilder.Entity("DiscordScraper.Storage.Entities.RawMessageEditEntity", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("MessageId", "EditedAt");

                    b.ToTable("raw_message_edits", (string)null);
                });

            modelBuilder.Entity("DiscordScraper.Storage.Entities.RawMessageEntity", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("MessageId");

                    b.HasIndex("ChannelId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_raw_messages_channel_created");

                    b.HasIndex("GuildId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_raw_messages_guild_created");

                    b.ToTable("raw_messages", (string)null);
                });

            modelBuilder.Entity("DiscordScraper.Storage.Entities.RawSyncStateEntity", b =>
                {
                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<int>("ConsecutiveErrors")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("consecutive_errors");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<long>("LastMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("last_message_id");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.HasKey("ChannelId");

                    b.ToTable("raw_sync_state", (string)null);
                });

            modelBuilder.Entity("DiscordScraper.Storage.Entities.MessageEnrichmentEntity", b =>
                {
                    b.HasOne("DiscordScraper.Storage.Entities.MessageEntity", "Message")
                        .WithOne("Enrichment")
                        .HasForeignKey("DiscordScraper.Storage.Entities.MessageEnrichmentEntity", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("DiscordScraper.Storage.Entities.MessageEntity", b =>
                {
                    b.HasOne("DiscordScraper.Storage.Entities.RawMessageEntity", null)
                        .WithOne()
                        .HasForeignKey("DiscordScraper.Storage.Entities.MessageEntity", "MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordScraper.Storage.Entities.MessageEntity", b =>
                {
                    b.Navigation("Enrichment");
                });
#pragma warning restore 612, 618
        }
    }
}
